// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Db;

#nullable disable

namespace backend.Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.Models.Project", b =>
                {
                    b.Property<int>("IdProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdProject");

                    b.Property<string>("NameProject")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NameProject");

                    b.Property<string>("StatusProject")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("StatusProject");

                    b.HasKey("IdProject");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("backend.Models.Task", b =>
                {
                    b.Property<int>("IdTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTask");

                    b.Property<DateTime>("DateTask")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DateTask");

                    b.Property<string>("ImportanceTask")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ImportanceTask");

                    b.Property<string>("NameTask")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NameTask");

                    b.Property<string>("StatusTask")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("StatusTask");

                    b.HasKey("IdTask");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("backend.Models.TaskDepartment", b =>
                {
                    b.Property<int>("IdDepartment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDepartment")
                        .HasColumnOrder(0);

                    b.Property<string>("NameDepartment")
                        .IsRequired()
                        .HasColumnType("varchar(75)")
                        .HasColumnName("NameDepartment")
                        .HasColumnOrder(2);

                    b.HasKey("IdDepartment");

                    b.ToTable("TaskDepartment");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
